FROM 265565150187.dkr.ecr.us-west-2.amazonaws.com/awslambda/python3.8-runtime:base-image-multi-arch

WORKDIR /var/task
COPY ./ ./

# This is to verify env vars are parsed correctly before executing the function
ENV MyEnv="4=4"