ARG IMAGE_ARCH
FROM public.ecr.aws/lambda/python:3.12-$IMAGE_ARCH

WORKDIR /var/task
COPY ./ ./
# Copy extension
ADD bash-extension /opt/extensions/
# This is to verify env vars are parsed correctly before executing the function
ENV MyEnv="4=4"
