name: Run Integration Tests

on:
  pull_request:
    branches:
      - develop
      - main
  merge_group:
    
permissions:
  contents: read

jobs:
  go-tests:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v6
        - name: run go tests
          run: make tests-with-docker
  integ-tests-x86:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v6
        - uses: actions/setup-python@v6
          with:
            python-version: '3.11'
        - name: run integration tests
          run: make integ-tests-with-docker-x86-64
  integ-tests-arm64:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v6
        - uses: actions/setup-python@v6
          with:
            python-version: '3.11'
        - name: run integration tests
          run: make integ-tests-with-docker-arm64
  integ-tests-old:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v6
        - uses: actions/setup-python@v6
          with:
            python-version: '3.11'
        - name: run integration tests
          run: make integ-tests-with-docker-old